// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model.Errors
{
  using System.Text.Json.Serialization;

  [JsonConverter(typeof(JsonStringEnumConverter<CreateOnchainTransactionBadRequestSubcode>))]
  public enum CreateOnchainTransactionBadRequestSubcode
  {
    PORTFOLIO_ID_REQUIRED,
    PORTFOLIO_ID_INVALID,
    WALLET_ID_REQUIRED,
    WALLET_ID_INVALID,
    WALLET_TYPE_NOT_SUPPORTED,
    ONCHAIN_TRANSACTION_REQUEST_INVALID,
    ONCHAIN_TRANSACTION_RAW_UNSIGNED_TXN_REQUIRED,
    ONCHAIN_TRANSACTION_RAW_UNSIGNED_TXN_INVALID,
    ONCHAIN_TRANSACTION_EVM_PARAMS_REQUIRED,
    ONCHAIN_TRANSACTION_EVM_PARAMS_INVALID,
    ONCHAIN_TRANSACTION_REPLACED_TRANSACTION_ID_INVALID,
    ONCHAIN_TRANSACTION_DISABLE_DYNAMIC_NONCE_INVALID,
    ONCHAIN_TRANSACTION_CHAIN_ID_REQUIRED,
    ONCHAIN_TRANSACTION_CHAIN_ID_INVALID,
    ONCHAIN_TRANSACTION_NETWORK_NAME_REQUIRED,
    ONCHAIN_TRANSACTION_RPC_URL_INVALID
  }
}
