// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model.Errors
{
  using System.Text.Json.Serialization;

  [JsonConverter(typeof(JsonStringEnumConverter<CreateAllocationBadRequestSubcode>))]
  public enum CreateAllocationBadRequestSubcode
  {
    PORTFOLIO_TYPE_UNSUPPORTED,
    PORTFOLIO_ID_INVALID,
    ALLOCATION_ID_REQUIRED,
    ALLOCATION_NETTING_ID_REQUIRED,
    ALLOCATION_REQUEST_INVALID,
    ALLOCATION_PRECONDITION_FAILED,
    ALLOCATION_SOURCE_PORTFOLIO_ID_REQUIRED,
    ALLOCATION_DESTINATION_PORTFOLIO_ID_REQUIRED,
    ALLOCATION_ORDERS_MIXED_SIDES,
    ALLOCATION_ORDERS_MIXED_PRODUCTS,
    ALLOCATION_ORDER_NOT_TERMINAL,
    ALLOCATION_ORDER_TOO_OLD,
    ALLOCATION_ORDER_ALREADY_ALLOCATED
  }
}
