// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model.Errors
{
  using System.Text.Json.Serialization;

  [JsonConverter(typeof(JsonStringEnumConverter<CreateOrderBadRequestSubcode>))]
  public enum CreateOrderBadRequestSubcode
  {
    ENTITY_ID_INVALID,
    PORTFOLIO_ID_REQUIRED,
    PORTFOLIO_ID_INVALID,
    BUYING_POWER_CURRENCY_INVALID,
    BUYING_POWER_FAILED_PRECONDITION,
    ORDER_REQUEST_INVALID,
    ORDER_STOP_LIMIT_NOT_ENABLED,
    ORDER_PEG_NOT_ENABLED,
    ORDER_DUPLICATE_CLIENT_ORDER_ID,
    ORDER_REJECTED,
    ORDER_PRODUCT_ID_INVALID,
    ORDER_TYPE_NOT_ALLOWED,
    ORDER_TIF_NOT_ENABLED,
    ORDER_FAILED_PRECONDITION,
    ORDER_SIDE_INVALID,
    ORDER_SIZE_REQUIRED,
    ORDER_SIZE_INVALID,
    ORDER_DISPLAY_SIZE_INVALID,
    ORDER_PRICE_INVALID,
    ORDER_STOP_PRICE_INVALID,
    ORDER_TIME_IN_FORCE_INVALID,
    ORDER_TIME_RANGE_INVALID,
    ORDER_PEG_OFFSET_TYPE_INVALID
  }
}
