// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model.Errors
{
  using System.Text.Json.Serialization;

  [JsonConverter(typeof(JsonStringEnumConverter<CreateWalletBadRequestSubcode>))]
  public enum CreateWalletBadRequestSubcode
  {
    PORTFOLIO_ID_INVALID,
    WALLET_TYPE_NOT_SUPPORTED,
    WALLET_REQUEST_INVALID,
    WALLET_ONCHAIN_SYMBOLS_NOT_ALLOWED,
    WALLET_FAILED_PRECONDITION,
    WALLET_NETWORK_ID_REQUIRED,
    WALLET_NETWORK_INVALID,
    WALLET_ONCHAIN_SETUP_UNAVAILABLE,
    WALLET_NAME_REQUIRED,
    WALLET_SYMBOL_REQUIRED,
    WALLET_NETWORK_FAMILY_REQUIRED,
    WALLET_NETWORK_FAMILY_NOT_ALLOWED,
    WALLET_NETWORK_TYPE_REQUIRED
  }
}
