// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model.Errors
{
  using System.Text.Json.Serialization;

  [JsonConverter(typeof(JsonStringEnumConverter<PortfolioStakingUnstakeBadRequestSubcode>))]
  public enum PortfolioStakingUnstakeBadRequestSubcode
  {
    PORTFOLIO_ID_REQUIRED,
    PORTFOLIO_ID_INVALID,
    WALLET_EXTERNAL_ID_INVALID,
    STAKING_REQUEST_INVALID,
    STAKING_CURRENCY_UNSUPPORTED,
    STAKING_AMOUNT_REQUIRED,
    STAKING_AMOUNT_INVALID,
    STAKING_AMOUNT_EXCEEDS_UNBONDABLE_BALANCE,
    STAKING_NO_ELIGIBLE_WALLETS,
    STAKING_BALANCE_NOT_FOUND,
    STAKING_PROVIDER_NO_UNBONDABLE_BALANCE,
    STAKING_IDEMPOTENCY_KEY_REQUIRED,
    STAKING_IDEMPOTENCY_KEY_INVALID,
    STAKING_CURRENCY_SYMBOL_REQUIRED,
    STAKING_AMOUNT_VALIDATOR_PROVIDER_CONFLICT,
    STAKING_VALIDATOR_PROVIDER_REQUIRED,
    STAKING_VALIDATOR_PROVIDER_NOT_SUPPORTED
  }
}
