// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model.Errors
{
  using System.Text.Json.Serialization;

  [JsonConverter(typeof(JsonStringEnumConverter<ServiceUnavailableSubcode>))]
  public enum ServiceUnavailableSubcode
  {
    SERVER_MAINTENANCE_MODE_ACTIVE,
    ORDER_SERVICE_UNAVAILABLE,
    WALLET_SERVICE_UNAVAILABLE,
    ASSET_SERVICE_UNAVAILABLE,
    FINANCING_SERVICE_UNAVAILABLE,
    TRANSACTION_SERVICE_UNAVAILABLE,
    STAKING_SERVICE_UNAVAILABLE,
    ADVANCED_TRANSFER_SERVICE_UNAVAILABLE
  }
}
