// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model.Errors
{
  using System.Text.Json.Serialization;

  [JsonConverter(typeof(JsonStringEnumConverter<StakingInitiateBadRequestSubcode>))]
  public enum StakingInitiateBadRequestSubcode
  {
    ENTITY_ID_INVALID,
    PORTFOLIO_ID_REQUIRED,
    PORTFOLIO_ID_INVALID,
    WALLET_ID_REQUIRED,
    WALLET_ID_INVALID,
    WALLET_TYPE_NOT_SUPPORTED,
    WALLET_EXTERNAL_ID_INVALID,
    STAKING_REQUEST_INVALID,
    STAKING_CURRENCY_UNSUPPORTED,
    STAKING_PRECONDITION_FAILED,
    STAKING_AMOUNT_REQUIRED,
    STAKING_AMOUNT_INVALID,
    STAKING_INSUFFICIENT_BALANCE,
    STAKING_WALLET_OR_PORTFOLIO_INVALID,
    STAKING_AMOUNT_EXCEEDS_UNBONDABLE_BALANCE,
    STAKING_WALLET_COLD_ADDRESS_NOT_FOUND,
    STAKING_NO_VALIDATORS_AVAILABLE,
    STAKING_END_DATE_INVALID,
    STAKING_CUSTOM_AMOUNT_NOT_SUPPORTED,
    STAKING_VALIDATOR_ADDRESS_NOT_SUPPORTED,
    STAKING_DESTINATION_ADDRESS_INVALID,
    STAKING_ACTION_TYPE_UNSUPPORTED,
    STAKING_UNSTAKE_NOT_AVAILABLE
  }
}
