// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model.Enums
{
  using System.Text.Json.Serialization;

  /// <summary>
  /// The general type of a derivative product.
  /// - DERIVATIVE_PRODUCT_TYPE_UNSPECIFIED: Unknown product type.
  /// - DERIVATIVE_PRODUCT_TYPE_SPOT: Spot product.
  /// - DERIVATIVE_PRODUCT_TYPE_FUTURE: Future product.
  /// - DERIVATIVE_PRODUCT_TYPE_EQUITY: Equity product.
  /// - DERIVATIVE_PRODUCT_TYPE_PREDICTION_MARKET: Prediction market product.
  /// - DERIVATIVE_PRODUCT_TYPE_OPTION: Option product.
  /// - DERIVATIVE_PRODUCT_TYPE_BASIS: Basis product.
  /// - DERIVATIVE_PRODUCT_TYPE_EQUITY_OPTION: Equity option product.
  /// - DERIVATIVE_PRODUCT_TYPE_FUTURE_COMBO: Future combo product.
  /// - DERIVATIVE_PRODUCT_TYPE_OPTION_COMBO: Option combo product.
  /// </summary>
  [JsonConverter(typeof(JsonStringEnumConverter<DerivativeProductType>))]
  public enum DerivativeProductType
  {
    /// <summary>
    /// Spot product.
    /// </summary>
    DERIVATIVE_PRODUCT_TYPE_SPOT,
    /// <summary>
    /// Future product.
    /// </summary>
    DERIVATIVE_PRODUCT_TYPE_FUTURE,
    /// <summary>
    /// Equity product.
    /// </summary>
    DERIVATIVE_PRODUCT_TYPE_EQUITY,
    /// <summary>
    /// Prediction market product.
    /// </summary>
    DERIVATIVE_PRODUCT_TYPE_PREDICTION_MARKET,
    /// <summary>
    /// Option product.
    /// </summary>
    DERIVATIVE_PRODUCT_TYPE_OPTION,
    /// <summary>
    /// Basis product.
    /// </summary>
    DERIVATIVE_PRODUCT_TYPE_BASIS,
    /// <summary>
    /// Equity option product.
    /// </summary>
    DERIVATIVE_PRODUCT_TYPE_EQUITY_OPTION,
    /// <summary>
    /// Future combo product.
    /// </summary>
    DERIVATIVE_PRODUCT_TYPE_FUTURE_COMBO,
    /// <summary>
    /// Option combo product.
    /// </summary>
    DERIVATIVE_PRODUCT_TYPE_OPTION_COMBO
  }
}
