// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  /// <summary>
  /// RewardsRateTier is a single tier in the rewards rate card.
  /// </summary>

  public class BetaRewardsRateTier
  {
    /// <summary>
    /// Rate for this tier.
    /// </summary>
    public string? Rate { get; set; }
    /// <summary>
    /// Lower bound of the tier&#39;s qualifying criteria (e.g. balance floor).
    /// </summary>
    public string? LowerLimit { get; set; }
    /// <summary>
    /// Upper bound of the tier&#39;s qualifying criteria.
    /// </summary>
    public string? UpperLimit { get; set; }
    /// <summary>
    /// RewardsRateTierType describes what a rewards rate tier is scoped by.
    /// </summary>
    public BetaRewardsRateTierType? CriteriaType { get; set; }
    public BetaRewardsRateTier() { }

    public BetaRewardsRateTier(Builder builder)
    {
      this.Rate = builder.rate;
      this.LowerLimit = builder.lowerLimit;
      this.UpperLimit = builder.upperLimit;
      this.CriteriaType = builder.criteriaType;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? rate;
      internal string? lowerLimit;
      internal string? upperLimit;
      internal BetaRewardsRateTierType? criteriaType;
#pragma warning restore SA1307, SA1401
      public Builder WithRate(string? rate)
      {
        this.rate = rate;
        return this;
      }
      public Builder WithLowerLimit(string? lowerLimit)
      {
        this.lowerLimit = lowerLimit;
        return this;
      }
      public Builder WithUpperLimit(string? upperLimit)
      {
        this.upperLimit = upperLimit;
        return this;
      }
      public Builder WithCriteriaType(BetaRewardsRateTierType? criteriaType)
      {
        this.criteriaType = criteriaType;
        return this;
      }
      public BetaRewardsRateTier Build()
      {
        return new BetaRewardsRateTier(this);
      }
    }
  }

}
