// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  /// <summary>
  /// ComboLeg describes a single leg within an options combo order.
  /// </summary>

  public class ComboLeg
  {
    /// <summary>
    /// The product identifier for the options instrument (e.g., \&quot;BTC-28MAR25-50000-C\&quot;).
    /// </summary>
    public string? ProductId { get; set; }
    public string? Quantity { get; set; }
    /// <summary>
    /// - UNKNOWN_ORDER_SIDE: nil value.
    /// - BUY: Buy order.
    /// - SELL: Sell order.
    /// </summary>
    public OrderSide? Side { get; set; }
    public ComboLeg() { }

    public ComboLeg(Builder builder)
    {
      this.ProductId = builder.productId;
      this.Quantity = builder.quantity;
      this.Side = builder.side;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? productId;
      internal string? quantity;
      internal OrderSide? side;
#pragma warning restore SA1307, SA1401
      public Builder WithProductId(string? productId)
      {
        this.productId = productId;
        return this;
      }
      public Builder WithQuantity(string? quantity)
      {
        this.quantity = quantity;
        return this;
      }
      public Builder WithSide(OrderSide? side)
      {
        this.side = side;
        return this;
      }
      public ComboLeg Build()
      {
        return new ComboLeg(this);
      }
    }
  }

}
