// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  /// <summary>
  /// A single fee tier in the progressive stablecoin conversion schedule.
  /// </summary>

  public class ConversionFeeTier
  {
    /// <summary>
    /// Inclusive lower bound for the tier in USD.
    /// </summary>
    public string? MinThreshold { get; set; }
    /// <summary>
    /// Exclusive upper bound for the tier in USD. Empty string for the highest, unbounded tier.
    /// </summary>
    public string? MaxThreshold { get; set; }
    /// <summary>
    /// Tier rate in basis points.
    /// </summary>
    public string? RateBps { get; set; }
    public ConversionFeeTier() { }

    public ConversionFeeTier(Builder builder)
    {
      this.MinThreshold = builder.minThreshold;
      this.MaxThreshold = builder.maxThreshold;
      this.RateBps = builder.rateBps;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? minThreshold;
      internal string? maxThreshold;
      internal string? rateBps;
#pragma warning restore SA1307, SA1401
      public Builder WithMinThreshold(string? minThreshold)
      {
        this.minThreshold = minThreshold;
        return this;
      }
      public Builder WithMaxThreshold(string? maxThreshold)
      {
        this.maxThreshold = maxThreshold;
        return this;
      }
      public Builder WithRateBps(string? rateBps)
      {
        this.rateBps = rateBps;
        return this;
      }
      public ConversionFeeTier Build()
      {
        return new ConversionFeeTier(this);
      }
    }
  }

}
