// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  /// <summary>
  /// Per-pair conversion fee row: month-to-date net conversion volume and.
  /// the applicable progressive fee tiers for an organization.
  /// </summary>

  public class ConversionFee
  {
    /// <summary>
    /// Source currency ticker.
    /// </summary>
    public string? FromCurrency { get; set; }
    /// <summary>
    /// Destination currency ticker.
    /// </summary>
    public string? ToCurrency { get; set; }
    /// <summary>
    /// Month-to-date net conversion volume denominated in from_currency, aggregated at the owning organization level. Positive &#x3D; net from-&gt;to, negative &#x3D; net to-&gt;from.
    /// </summary>
    public string? NetConversionVolumeMtd { get; set; }
    /// <summary>
    /// Progressive fee tiers applicable to this organization for this pair. Tiers are ordered from lowest to highest threshold.
    /// </summary>
    public List<ConversionFeeTier>? FeeTiers { get; set; }
    public ConversionFee() { }

    public ConversionFee(Builder builder)
    {
      this.FromCurrency = builder.fromCurrency;
      this.ToCurrency = builder.toCurrency;
      this.NetConversionVolumeMtd = builder.netConversionVolumeMtd;
      this.FeeTiers = builder.feeTiers;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? fromCurrency;
      internal string? toCurrency;
      internal string? netConversionVolumeMtd;
      internal List<ConversionFeeTier>? feeTiers;
#pragma warning restore SA1307, SA1401
      public Builder WithFromCurrency(string? fromCurrency)
      {
        this.fromCurrency = fromCurrency;
        return this;
      }
      public Builder WithToCurrency(string? toCurrency)
      {
        this.toCurrency = toCurrency;
        return this;
      }
      public Builder WithNetConversionVolumeMtd(string? netConversionVolumeMtd)
      {
        this.netConversionVolumeMtd = netConversionVolumeMtd;
        return this;
      }
      public Builder WithFeeTiers(List<ConversionFeeTier>? feeTiers)
      {
        this.feeTiers = feeTiers;
        return this;
      }
      public ConversionFee Build()
      {
        return new ConversionFee(this);
      }
    }
  }

}
