// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  /// <summary>
  /// Currency metadata of the custom stablecoin asset for the reward program.
  /// </summary>

  public class CustomStablecoinAsset
  {
    /// <summary>
    /// The asset symbol (e.g. USDC, USDF)
    /// </summary>
    public string? Symbol { get; set; }
    public CustomStablecoinAsset() { }

    public CustomStablecoinAsset(Builder builder)
    {
      this.Symbol = builder.symbol;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? symbol;
#pragma warning restore SA1307, SA1401
      public Builder WithSymbol(string? symbol)
      {
        this.symbol = symbol;
        return this;
      }
      public CustomStablecoinAsset Build()
      {
        return new CustomStablecoinAsset(this);
      }
    }
  }

}
