// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  /// <summary>
  /// Balances for a single settlement currency within an international derivatives portfolio.
  /// </summary>

  public class DerivativesCurrencyBalance
  {
    /// <summary>
    /// Settlement currency
    /// </summary>
    public string? Currency { get; set; }
    /// <summary>
    /// Cash balance for the currency
    /// </summary>
    public string? Balance { get; set; }
    /// <summary>
    /// Unrealized PNL
    /// </summary>
    public string? UnrealizedPnl { get; set; }
    /// <summary>
    /// Realized PNL
    /// </summary>
    public string? RealizedPnl { get; set; }
    /// <summary>
    /// Initial margin
    /// </summary>
    public string? InitialMargin { get; set; }
    /// <summary>
    /// Maintenance margin
    /// </summary>
    public string? MaintenanceMargin { get; set; }
    /// <summary>
    /// Margin balance for the currency
    /// </summary>
    public string? MarginBalance { get; set; }
    /// <summary>
    /// Option value for the currency
    /// </summary>
    public string? OptionValue { get; set; }
    /// <summary>
    /// Margin excess for the currency (negative indicates a margin deficit)
    /// </summary>
    public string? MarginExcess { get; set; }
    /// <summary>
    /// Margin utilization for the currency, as a percentage
    /// </summary>
    public string? MarginUtilization { get; set; }
    /// <summary>
    /// The margin health state of an FCM account.
    /// - FCM_MARGIN_HEALTH_STATE_UNSPECIFIED: Unspecified margin health state.
    /// - FCM_MARGIN_HEALTH_STATE_HEALTHY: Account margin is healthy.
    /// - FCM_MARGIN_HEALTH_STATE_RESTRICTED: Account margin is restricted.
    /// - FCM_MARGIN_HEALTH_STATE_PRE_LIQUIDATION: Account is approaching liquidation.
    /// - FCM_MARGIN_HEALTH_STATE_LIQUIDATION: Account is in liquidation.
    /// </summary>
    public FcmMarginHealthState? MarginHealthState { get; set; }
    public DerivativesCurrencyBalance() { }

    public DerivativesCurrencyBalance(Builder builder)
    {
      this.Currency = builder.currency;
      this.Balance = builder.balance;
      this.UnrealizedPnl = builder.unrealizedPnl;
      this.RealizedPnl = builder.realizedPnl;
      this.InitialMargin = builder.initialMargin;
      this.MaintenanceMargin = builder.maintenanceMargin;
      this.MarginBalance = builder.marginBalance;
      this.OptionValue = builder.optionValue;
      this.MarginExcess = builder.marginExcess;
      this.MarginUtilization = builder.marginUtilization;
      this.MarginHealthState = builder.marginHealthState;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? currency;
      internal string? balance;
      internal string? unrealizedPnl;
      internal string? realizedPnl;
      internal string? initialMargin;
      internal string? maintenanceMargin;
      internal string? marginBalance;
      internal string? optionValue;
      internal string? marginExcess;
      internal string? marginUtilization;
      internal FcmMarginHealthState? marginHealthState;
#pragma warning restore SA1307, SA1401
      public Builder WithCurrency(string? currency)
      {
        this.currency = currency;
        return this;
      }
      public Builder WithBalance(string? balance)
      {
        this.balance = balance;
        return this;
      }
      public Builder WithUnrealizedPnl(string? unrealizedPnl)
      {
        this.unrealizedPnl = unrealizedPnl;
        return this;
      }
      public Builder WithRealizedPnl(string? realizedPnl)
      {
        this.realizedPnl = realizedPnl;
        return this;
      }
      public Builder WithInitialMargin(string? initialMargin)
      {
        this.initialMargin = initialMargin;
        return this;
      }
      public Builder WithMaintenanceMargin(string? maintenanceMargin)
      {
        this.maintenanceMargin = maintenanceMargin;
        return this;
      }
      public Builder WithMarginBalance(string? marginBalance)
      {
        this.marginBalance = marginBalance;
        return this;
      }
      public Builder WithOptionValue(string? optionValue)
      {
        this.optionValue = optionValue;
        return this;
      }
      public Builder WithMarginExcess(string? marginExcess)
      {
        this.marginExcess = marginExcess;
        return this;
      }
      public Builder WithMarginUtilization(string? marginUtilization)
      {
        this.marginUtilization = marginUtilization;
        return this;
      }
      public Builder WithMarginHealthState(FcmMarginHealthState? marginHealthState)
      {
        this.marginHealthState = marginHealthState;
        return this;
      }
      public DerivativesCurrencyBalance Build()
      {
        return new DerivativesCurrencyBalance(this);
      }
    }
  }

}
