// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  /// <summary>
  /// A single derivative position across all derivative product types.
  /// </summary>

  public class DerivativePosition
  {
    /// <summary>
    /// Product ID
    /// </summary>
    public string? ProductId { get; set; }
    public FcmPositionSide? Side { get; set; }
    /// <summary>
    /// Number of contracts
    /// </summary>
    public string? NumberOfContracts { get; set; }
    /// <summary>
    /// Daily realized PNL
    /// </summary>
    public string? DailyRealizedPnl { get; set; }
    /// <summary>
    /// Unrealized PNL
    /// </summary>
    public string? UnrealizedPnl { get; set; }
    /// <summary>
    /// Current price of position
    /// </summary>
    public string? CurrentPrice { get; set; }
    /// <summary>
    /// Average entry price
    /// </summary>
    public string? AvgEntryPrice { get; set; }
    /// <summary>
    /// Expiration time of position
    /// </summary>
    public DateTime? ExpirationTime { get; set; }
    /// <summary>
    /// The general type of a derivative product.
    /// - DERIVATIVE_PRODUCT_TYPE_UNSPECIFIED: Unknown product type.
    /// - DERIVATIVE_PRODUCT_TYPE_SPOT: Spot product.
    /// - DERIVATIVE_PRODUCT_TYPE_FUTURE: Future product.
    /// - DERIVATIVE_PRODUCT_TYPE_EQUITY: Equity product.
    /// - DERIVATIVE_PRODUCT_TYPE_PREDICTION_MARKET: Prediction market product.
    /// - DERIVATIVE_PRODUCT_TYPE_OPTION: Option product.
    /// - DERIVATIVE_PRODUCT_TYPE_BASIS: Basis product.
    /// - DERIVATIVE_PRODUCT_TYPE_EQUITY_OPTION: Equity option product.
    /// - DERIVATIVE_PRODUCT_TYPE_FUTURE_COMBO: Future combo product.
    /// - DERIVATIVE_PRODUCT_TYPE_OPTION_COMBO: Option combo product.
    /// </summary>
    public DerivativeProductType? ProductType { get; set; }
    /// <summary>
    /// Settlement currency
    /// </summary>
    public string? Currency { get; set; }
    /// <summary>
    /// Options-specific details for a derivative position, including greeks.
    /// </summary>
    public OptionsDetails? OptionsDetails { get; set; }
    /// <summary>
    /// Venue ID of the position
    /// </summary>
    public string? VenueId { get; set; }
    public DerivativePosition() { }

    public DerivativePosition(Builder builder)
    {
      this.ProductId = builder.productId;
      this.Side = builder.side;
      this.NumberOfContracts = builder.numberOfContracts;
      this.DailyRealizedPnl = builder.dailyRealizedPnl;
      this.UnrealizedPnl = builder.unrealizedPnl;
      this.CurrentPrice = builder.currentPrice;
      this.AvgEntryPrice = builder.avgEntryPrice;
      this.ExpirationTime = builder.expirationTime;
      this.ProductType = builder.productType;
      this.Currency = builder.currency;
      this.OptionsDetails = builder.optionsDetails;
      this.VenueId = builder.venueId;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? productId;
      internal FcmPositionSide? side;
      internal string? numberOfContracts;
      internal string? dailyRealizedPnl;
      internal string? unrealizedPnl;
      internal string? currentPrice;
      internal string? avgEntryPrice;
      internal DateTime? expirationTime;
      internal DerivativeProductType? productType;
      internal string? currency;
      internal OptionsDetails? optionsDetails;
      internal string? venueId;
#pragma warning restore SA1307, SA1401
      public Builder WithProductId(string? productId)
      {
        this.productId = productId;
        return this;
      }
      public Builder WithSide(FcmPositionSide? side)
      {
        this.side = side;
        return this;
      }
      public Builder WithNumberOfContracts(string? numberOfContracts)
      {
        this.numberOfContracts = numberOfContracts;
        return this;
      }
      public Builder WithDailyRealizedPnl(string? dailyRealizedPnl)
      {
        this.dailyRealizedPnl = dailyRealizedPnl;
        return this;
      }
      public Builder WithUnrealizedPnl(string? unrealizedPnl)
      {
        this.unrealizedPnl = unrealizedPnl;
        return this;
      }
      public Builder WithCurrentPrice(string? currentPrice)
      {
        this.currentPrice = currentPrice;
        return this;
      }
      public Builder WithAvgEntryPrice(string? avgEntryPrice)
      {
        this.avgEntryPrice = avgEntryPrice;
        return this;
      }
      public Builder WithExpirationTime(DateTime? expirationTime)
      {
        this.expirationTime = expirationTime;
        return this;
      }
      public Builder WithProductType(DerivativeProductType? productType)
      {
        this.productType = productType;
        return this;
      }
      public Builder WithCurrency(string? currency)
      {
        this.currency = currency;
        return this;
      }
      public Builder WithOptionsDetails(OptionsDetails? optionsDetails)
      {
        this.optionsDetails = optionsDetails;
        return this;
      }
      public Builder WithVenueId(string? venueId)
      {
        this.venueId = venueId;
        return this;
      }
      public DerivativePosition Build()
      {
        return new DerivativePosition(this);
      }
    }
  }

}
