// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  /// <summary>
  /// OptionProductDetails contains details specific to option products.
  /// </summary>

  public class OptionProductDetails
  {
    /// <summary>
    /// The type of an option position.
    /// - OPTION_TYPE_UNSPECIFIED: Unspecified option type.
    /// - OPTION_TYPE_CALL: Call option.
    /// - OPTION_TYPE_PUT: Put option.
    /// </summary>
    public OptionType? OptionType { get; set; }
    /// <summary>
    /// Strike price of the option
    /// </summary>
    public string? Strike { get; set; }
    /// <summary>
    /// Contract root unit (underlying asset)
    /// </summary>
    public string? ContractRootUnit { get; set; }
    /// <summary>
    /// Currency the option settles in
    /// </summary>
    public string? SettlementCurrency { get; set; }
    /// <summary>
    /// Contract code identifier
    /// </summary>
    public string? ContractCode { get; set; }
    /// <summary>
    /// Descriptive name for the product group
    /// </summary>
    public string? GroupDescription { get; set; }
    /// <summary>
    /// Contract size
    /// </summary>
    public string? ContractSize { get; set; }
    /// <summary>
    /// Contract expiry timestamp
    /// </summary>
    public DateTime? ContractExpiry { get; set; }
    /// <summary>
    /// - SETTLEMENT_PERIOD_UNSPECIFIED: Unspecified settlement period.
    /// - SETTLEMENT_PERIOD_PERPETUAL: Contract never expires.
    /// - SETTLEMENT_PERIOD_DAY: Contract expires daily.
    /// - SETTLEMENT_PERIOD_WEEK: Contract expires weekly.
    /// - SETTLEMENT_PERIOD_MONTH: Contract expires monthly.
    /// </summary>
    public SettlementPeriod? SettlementPeriod { get; set; }
    /// <summary>
    /// - SETTLEMENT_MODEL_UNSPECIFIED: Unspecified settlement model.
    /// - SETTLEMENT_MODEL_LINEAR: Settles in the quote currency.
    /// - SETTLEMENT_MODEL_INVERSE: Settles in the base currency.
    /// </summary>
    public SettlementModel? SettlementModel { get; set; }
    /// <summary>
    /// Currency the option is quoted against
    /// </summary>
    public string? CounterCurrency { get; set; }
    /// <summary>
    /// Smallest tradable quantity of the contract
    /// </summary>
    public string? LotSize { get; set; }
    /// <summary>
    /// Tiered price increments that override price_increment above a threshold; empty when a single price_increment applies
    /// </summary>
    public List<PriceIncrementStep>? PriceIncrementSteps { get; set; }
    public OptionProductDetails() { }

    public OptionProductDetails(Builder builder)
    {
      this.OptionType = builder.optionType;
      this.Strike = builder.strike;
      this.ContractRootUnit = builder.contractRootUnit;
      this.SettlementCurrency = builder.settlementCurrency;
      this.ContractCode = builder.contractCode;
      this.GroupDescription = builder.groupDescription;
      this.ContractSize = builder.contractSize;
      this.ContractExpiry = builder.contractExpiry;
      this.SettlementPeriod = builder.settlementPeriod;
      this.SettlementModel = builder.settlementModel;
      this.CounterCurrency = builder.counterCurrency;
      this.LotSize = builder.lotSize;
      this.PriceIncrementSteps = builder.priceIncrementSteps;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal OptionType? optionType;
      internal string? strike;
      internal string? contractRootUnit;
      internal string? settlementCurrency;
      internal string? contractCode;
      internal string? groupDescription;
      internal string? contractSize;
      internal DateTime? contractExpiry;
      internal SettlementPeriod? settlementPeriod;
      internal SettlementModel? settlementModel;
      internal string? counterCurrency;
      internal string? lotSize;
      internal List<PriceIncrementStep>? priceIncrementSteps;
#pragma warning restore SA1307, SA1401
      public Builder WithOptionType(OptionType? optionType)
      {
        this.optionType = optionType;
        return this;
      }
      public Builder WithStrike(string? strike)
      {
        this.strike = strike;
        return this;
      }
      public Builder WithContractRootUnit(string? contractRootUnit)
      {
        this.contractRootUnit = contractRootUnit;
        return this;
      }
      public Builder WithSettlementCurrency(string? settlementCurrency)
      {
        this.settlementCurrency = settlementCurrency;
        return this;
      }
      public Builder WithContractCode(string? contractCode)
      {
        this.contractCode = contractCode;
        return this;
      }
      public Builder WithGroupDescription(string? groupDescription)
      {
        this.groupDescription = groupDescription;
        return this;
      }
      public Builder WithContractSize(string? contractSize)
      {
        this.contractSize = contractSize;
        return this;
      }
      public Builder WithContractExpiry(DateTime? contractExpiry)
      {
        this.contractExpiry = contractExpiry;
        return this;
      }
      public Builder WithSettlementPeriod(SettlementPeriod? settlementPeriod)
      {
        this.settlementPeriod = settlementPeriod;
        return this;
      }
      public Builder WithSettlementModel(SettlementModel? settlementModel)
      {
        this.settlementModel = settlementModel;
        return this;
      }
      public Builder WithCounterCurrency(string? counterCurrency)
      {
        this.counterCurrency = counterCurrency;
        return this;
      }
      public Builder WithLotSize(string? lotSize)
      {
        this.lotSize = lotSize;
        return this;
      }
      public Builder WithPriceIncrementSteps(List<PriceIncrementStep>? priceIncrementSteps)
      {
        this.priceIncrementSteps = priceIncrementSteps;
        return this;
      }
      public OptionProductDetails Build()
      {
        return new OptionProductDetails(this);
      }
    }
  }

}
