// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  /// <summary>
  /// Options-specific details for a derivative position, including greeks.
  /// </summary>

  public class OptionsDetails
  {
    /// <summary>
    /// Delta greek
    /// </summary>
    public string? Delta { get; set; }
    /// <summary>
    /// Gamma greek
    /// </summary>
    public string? Gamma { get; set; }
    /// <summary>
    /// Theta greek
    /// </summary>
    public string? Theta { get; set; }
    /// <summary>
    /// Vega greek
    /// </summary>
    public string? Vega { get; set; }
    /// <summary>
    /// Strike price
    /// </summary>
    public string? Strike { get; set; }
    /// <summary>
    /// The type of an option position.
    /// - OPTION_TYPE_UNSPECIFIED: Unspecified option type.
    /// - OPTION_TYPE_CALL: Call option.
    /// - OPTION_TYPE_PUT: Put option.
    /// </summary>
    public OptionType? OptionType { get; set; }
    public OptionsDetails() { }

    public OptionsDetails(Builder builder)
    {
      this.Delta = builder.delta;
      this.Gamma = builder.gamma;
      this.Theta = builder.theta;
      this.Vega = builder.vega;
      this.Strike = builder.strike;
      this.OptionType = builder.optionType;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? delta;
      internal string? gamma;
      internal string? theta;
      internal string? vega;
      internal string? strike;
      internal OptionType? optionType;
#pragma warning restore SA1307, SA1401
      public Builder WithDelta(string? delta)
      {
        this.delta = delta;
        return this;
      }
      public Builder WithGamma(string? gamma)
      {
        this.gamma = gamma;
        return this;
      }
      public Builder WithTheta(string? theta)
      {
        this.theta = theta;
        return this;
      }
      public Builder WithVega(string? vega)
      {
        this.vega = vega;
        return this;
      }
      public Builder WithStrike(string? strike)
      {
        this.strike = strike;
        return this;
      }
      public Builder WithOptionType(OptionType? optionType)
      {
        this.optionType = optionType;
        return this;
      }
      public OptionsDetails Build()
      {
        return new OptionsDetails(this);
      }
    }
  }

}
