// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  /// <summary>
  /// PriceIncrementStep overrides the product's price_increment for prices above a.
  /// threshold. A price takes the increment of the highest step whose threshold it.
  /// strictly exceeds, and the product's price_increment when it exceeds none.
  /// </summary>

  public class PriceIncrementStep
  {
    /// <summary>
    /// Prices strictly greater than this threshold use this step&#39;s price increment; a price equal to it takes the next lower step
    /// </summary>
    public string? PriceThreshold { get; set; }
    /// <summary>
    /// Minimum price increment applied to prices above the threshold
    /// </summary>
    public string? PriceIncrement { get; set; }
    public PriceIncrementStep() { }

    public PriceIncrementStep(Builder builder)
    {
      this.PriceThreshold = builder.priceThreshold;
      this.PriceIncrement = builder.priceIncrement;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? priceThreshold;
      internal string? priceIncrement;
#pragma warning restore SA1307, SA1401
      public Builder WithPriceThreshold(string? priceThreshold)
      {
        this.priceThreshold = priceThreshold;
        return this;
      }
      public Builder WithPriceIncrement(string? priceIncrement)
      {
        this.priceIncrement = priceIncrement;
        return this;
      }
      public PriceIncrementStep Build()
      {
        return new PriceIncrementStep(this);
      }
    }
  }

}
