// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  /// <summary>
  /// XMLiquidationSummary provides a summary of a single XM liquidation.
  /// </summary>

  public class XmLiquidationSummary
  {
    /// <summary>
    /// Financing liquidation UUID
    /// </summary>
    public string? LiquidationId { get; set; }
    /// <summary>
    /// - XM_LIQUIDATION_STATUS_PRE_LIQUIDATION: Liquidation is in the pre-liquidation phase.
    /// - XM_LIQUIDATION_STATUS_LIQUIDATING: Liquidation is actively in progress.
    /// - XM_LIQUIDATION_STATUS_LIQUIDATED: Liquidation has completed successfully.
    /// - XM_LIQUIDATION_STATUS_CANCELED: Liquidation was canceled.
    /// - XM_LIQUIDATION_STATUS_FAILED: Liquidation failed.
    /// </summary>
    public XmLiquidationStatus? Status { get; set; }
    /// <summary>
    /// USD notional shortfall amount that triggered the liquidation
    /// </summary>
    public string? ShortfallAmount { get; set; }
    /// <summary>
    /// USD notional amount that has been filled so far
    /// </summary>
    public string? FilledAmount { get; set; }
    /// <summary>
    /// USD notional amount remaining to be liquidated
    /// </summary>
    public string? RemainingAmount { get; set; }
    /// <summary>
    /// Timestamp when the liquidation was created
    /// </summary>
    public DateTime? CreatedAt { get; set; }
    /// <summary>
    /// Timestamp when the liquidation was completed
    /// </summary>
    public DateTime? CompletedAt { get; set; }
    public XmLiquidationSummary() { }

    public XmLiquidationSummary(Builder builder)
    {
      this.LiquidationId = builder.liquidationId;
      this.Status = builder.status;
      this.ShortfallAmount = builder.shortfallAmount;
      this.FilledAmount = builder.filledAmount;
      this.RemainingAmount = builder.remainingAmount;
      this.CreatedAt = builder.createdAt;
      this.CompletedAt = builder.completedAt;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? liquidationId;
      internal XmLiquidationStatus? status;
      internal string? shortfallAmount;
      internal string? filledAmount;
      internal string? remainingAmount;
      internal DateTime? createdAt;
      internal DateTime? completedAt;
#pragma warning restore SA1307, SA1401
      public Builder WithLiquidationId(string? liquidationId)
      {
        this.liquidationId = liquidationId;
        return this;
      }
      public Builder WithStatus(XmLiquidationStatus? status)
      {
        this.status = status;
        return this;
      }
      public Builder WithShortfallAmount(string? shortfallAmount)
      {
        this.shortfallAmount = shortfallAmount;
        return this;
      }
      public Builder WithFilledAmount(string? filledAmount)
      {
        this.filledAmount = filledAmount;
        return this;
      }
      public Builder WithRemainingAmount(string? remainingAmount)
      {
        this.remainingAmount = remainingAmount;
        return this;
      }
      public Builder WithCreatedAt(DateTime? createdAt)
      {
        this.createdAt = createdAt;
        return this;
      }
      public Builder WithCompletedAt(DateTime? completedAt)
      {
        this.completedAt = completedAt;
        return this;
      }
      public XmLiquidationSummary Build()
      {
        return new XmLiquidationSummary(this);
      }
    }
  }

}
