// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  /// <summary>
  /// XMLiquidationDetail provides detailed information about a single XM liquidation.
  /// </summary>

  public class XmLiquidationDetail
  {
    /// <summary>
    /// Financing liquidation UUID
    /// </summary>
    public string? LiquidationId { get; set; }
    /// <summary>
    /// - XM_LIQUIDATION_STATUS_PRE_LIQUIDATION: Liquidation is in the pre-liquidation phase.
    /// - XM_LIQUIDATION_STATUS_LIQUIDATING: Liquidation is actively in progress.
    /// - XM_LIQUIDATION_STATUS_LIQUIDATED: Liquidation has completed successfully.
    /// - XM_LIQUIDATION_STATUS_CANCELED: Liquidation was canceled.
    /// - XM_LIQUIDATION_STATUS_FAILED: Liquidation failed.
    /// </summary>
    public XmLiquidationStatus? Status { get; set; }
    /// <summary>
    /// USD notional shortfall amount that triggered the liquidation
    /// </summary>
    public string? ShortfallAmount { get; set; }
    /// <summary>
    /// Timestamp when the pre-liquidation phase started
    /// </summary>
    public DateTime? PreLiquidationStartTime { get; set; }
    /// <summary>
    /// XMSummary is the realtime evaluated XM margin model, containing positions and netting info.
    /// </summary>
    public XmSummary? MarginSummary { get; set; }
    /// <summary>
    /// Timestamp when active liquidation started
    /// </summary>
    public DateTime? LiquidationStartTime { get; set; }
    /// <summary>
    /// USD notional amount that has been filled so far
    /// </summary>
    public string? FilledAmount { get; set; }
    /// <summary>
    /// USD notional amount remaining to be liquidated
    /// </summary>
    public string? RemainingAmount { get; set; }
    /// <summary>
    /// Timestamp when the liquidation finished
    /// </summary>
    public DateTime? LiquidationFinishTime { get; set; }
    /// <summary>
    /// Per-asset breakdown of liquidated amounts
    /// </summary>
    public List<XmLiquidatedAsset>? AssetBreakdown { get; set; }
    public XmLiquidationDetail() { }

    public XmLiquidationDetail(Builder builder)
    {
      this.LiquidationId = builder.liquidationId;
      this.Status = builder.status;
      this.ShortfallAmount = builder.shortfallAmount;
      this.PreLiquidationStartTime = builder.preLiquidationStartTime;
      this.MarginSummary = builder.marginSummary;
      this.LiquidationStartTime = builder.liquidationStartTime;
      this.FilledAmount = builder.filledAmount;
      this.RemainingAmount = builder.remainingAmount;
      this.LiquidationFinishTime = builder.liquidationFinishTime;
      this.AssetBreakdown = builder.assetBreakdown;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? liquidationId;
      internal XmLiquidationStatus? status;
      internal string? shortfallAmount;
      internal DateTime? preLiquidationStartTime;
      internal XmSummary? marginSummary;
      internal DateTime? liquidationStartTime;
      internal string? filledAmount;
      internal string? remainingAmount;
      internal DateTime? liquidationFinishTime;
      internal List<XmLiquidatedAsset>? assetBreakdown;
#pragma warning restore SA1307, SA1401
      public Builder WithLiquidationId(string? liquidationId)
      {
        this.liquidationId = liquidationId;
        return this;
      }
      public Builder WithStatus(XmLiquidationStatus? status)
      {
        this.status = status;
        return this;
      }
      public Builder WithShortfallAmount(string? shortfallAmount)
      {
        this.shortfallAmount = shortfallAmount;
        return this;
      }
      public Builder WithPreLiquidationStartTime(DateTime? preLiquidationStartTime)
      {
        this.preLiquidationStartTime = preLiquidationStartTime;
        return this;
      }
      public Builder WithMarginSummary(XmSummary? marginSummary)
      {
        this.marginSummary = marginSummary;
        return this;
      }
      public Builder WithLiquidationStartTime(DateTime? liquidationStartTime)
      {
        this.liquidationStartTime = liquidationStartTime;
        return this;
      }
      public Builder WithFilledAmount(string? filledAmount)
      {
        this.filledAmount = filledAmount;
        return this;
      }
      public Builder WithRemainingAmount(string? remainingAmount)
      {
        this.remainingAmount = remainingAmount;
        return this;
      }
      public Builder WithLiquidationFinishTime(DateTime? liquidationFinishTime)
      {
        this.liquidationFinishTime = liquidationFinishTime;
        return this;
      }
      public Builder WithAssetBreakdown(List<XmLiquidatedAsset>? assetBreakdown)
      {
        this.assetBreakdown = assetBreakdown;
        return this;
      }
      public XmLiquidationDetail Build()
      {
        return new XmLiquidationDetail(this);
      }
    }
  }

}
