// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  /// <summary>
  /// XMLiquidatedAsset provides per-asset detail for a liquidation.
  /// </summary>

  public class XmLiquidatedAsset
  {
    /// <summary>
    /// Asset currency
    /// </summary>
    public string? Asset { get; set; }
    /// <summary>
    /// Amount (nominal) of the asset that has been liquidated
    /// </summary>
    public string? LiquidatedAmount { get; set; }
    /// <summary>
    /// USD notional value of the liquidated amount
    /// </summary>
    public string? LiquidatedNotional { get; set; }
    /// <summary>
    /// Amount (nominal) of the asset remaining to be liquidated
    /// </summary>
    public string? RemainingAmount { get; set; }
    /// <summary>
    /// USD notional value of the remaining amount
    /// </summary>
    public string? RemainingNotional { get; set; }
    public XmLiquidatedAsset() { }

    public XmLiquidatedAsset(Builder builder)
    {
      this.Asset = builder.asset;
      this.LiquidatedAmount = builder.liquidatedAmount;
      this.LiquidatedNotional = builder.liquidatedNotional;
      this.RemainingAmount = builder.remainingAmount;
      this.RemainingNotional = builder.remainingNotional;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? asset;
      internal string? liquidatedAmount;
      internal string? liquidatedNotional;
      internal string? remainingAmount;
      internal string? remainingNotional;
#pragma warning restore SA1307, SA1401
      public Builder WithAsset(string? asset)
      {
        this.asset = asset;
        return this;
      }
      public Builder WithLiquidatedAmount(string? liquidatedAmount)
      {
        this.liquidatedAmount = liquidatedAmount;
        return this;
      }
      public Builder WithLiquidatedNotional(string? liquidatedNotional)
      {
        this.liquidatedNotional = liquidatedNotional;
        return this;
      }
      public Builder WithRemainingAmount(string? remainingAmount)
      {
        this.remainingAmount = remainingAmount;
        return this;
      }
      public Builder WithRemainingNotional(string? remainingNotional)
      {
        this.remainingNotional = remainingNotional;
        return this;
      }
      public XmLiquidatedAsset Build()
      {
        return new XmLiquidatedAsset(this);
      }
    }
  }

}
